export const MEASUREMENTS = [
    "NECK",
    "BUST",
    "HIPS",
    "Legs",
    "Waist",
    "Height",
    "Top",
    "Length",
    "Upper arm",
    "Length from shoulder",
    "Length from shoulder to below knee",
    "Arm length",
    "Length from shoulder to waist",
    "Length from waist to ankle",
    "Thigh",
    "Calf",
    "Ankle",
    "Length from waist to below knee",
    "Around off shoulder",
    "Length from waist to desired skirt length",
    "Length from bust to waist",
    "Across chest one arm",
    "Shoulder Strap length",
    "Length from shoulder to ankle"
  ];